services:
  mysql:
    image: mysql:8.0.42
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: yourdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: ${DOCKER_USERNAME}/spring-backend:${TAG:-latest}
    container_name: spring-backend
    ports:
      - "8082:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=yourdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    restart: always

  frontend:
    image: ${DOCKER_USERNAME}/angular-frontend:${TAG:-latest}
    container_name: angular-frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
    restart: always

volumes:
  mysql-data: