apiVersion: v1
kind: Secret
metadata:
  name: spring-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk    # base64("rootpassword")
  MYSQL_USER: cmR1c2Vy                    # base64("rduser")
  MYSQL_PASSWORD: cGFzc3dvcmQ=           # base64("password")
